// ---------------------------------------------------------------------------
// Copyright:   (c) 2026 ff. Michael Amrhein (michael@adrhinum.de)
// License:     This program is part of a larger application. For license
//              details please read the file LICENSE.TXT provided together
//              with the application.
// ---------------------------------------------------------------------------
// $Source$
// $Revision$

//! Translation between HID usages and evdev key codes.
//!
//! The kernel's `hid-input` driver translates HID reports into evdev events
//! inside the kernel, and that translation is not callable from user space.
//! The daemon therefore carries its own mapping:
//!
//! - `hid_usage_to_keycode` — output direction: converts a `HidUsage` to the
//!   evdev `KEY_*` code written to the uinput virtual keyboard.
//! - `keycode_to_hid_usage` — input fallback: converts an evdev `KEY_*` code
//!   back to a `HidUsage` for devices that do not emit `MSC_SCAN` (older
//!   kernels, some virtual devices).  For devices that emit `MSC_SCAN`, the
//!   scan code already encodes the full HID usage as `(page << 16) | id` and
//!   `HidUsage::from_code` resolves it without any table lookup.
//!
//! Both directions are generated by `define_keycode!` from the single
//! declarative table in this module: each line pairs a `HidUsage` variant
//! with its evdev `KEY_*` code.  Because the generated `from_hid_usage`
//! match is exhaustive over `HidUsage`, a new HID usage without an evdev
//! entry fails to compile, so the two tables cannot drift apart.  Key code
//! values are derived from `include/uapi/linux/input-event-codes.h`.

use crate::common::hid_usage::HidUsage;

// ---------------------------------------------------------------------------
// Table-driven generation
// ---------------------------------------------------------------------------
//
// `define_keycode!` is the single source of truth for the Linux `Keycode`
// enum.  Each table line declares one variant:
//
//     Variant = N;
//
// where `N` is the kernel evdev `KEY_*` code.  Variant names mirror the
// `HidUsage` variants one-to-one; the macro uses them to generate both
// mapping directions alongside the enum itself, so the pairing is written
// exactly once.

macro_rules! define_keycode {
    {
        $( $variant:ident = $code:literal ; )*
    } => {
        /// Linux evdev key code.
        ///
        /// The discriminant is the kernel `KEY_*` value from
        /// `include/uapi/linux/input-event-codes.h`.  The variants mirror
        /// [`HidUsage`] one-to-one: every currently-defined HID usage has a
        /// stable evdev equivalent.
        #[repr(u16)]
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
        pub enum Keycode {
            $( $variant = $code, )*
        }

        impl Keycode {
            /// Construct a `Keycode` from a raw evdev `KEY_*` code.
            ///
            /// Returns `None` if the code does not match a defined variant.
            #[inline]
            pub const fn from_native(code: u16) -> Option<Self> {
                match code {
                    $( $code => Some(Self::$variant), )*
                    _ => None,
                }
            }

            /// Return the raw evdev `KEY_*` code.
            #[inline]
            pub const fn as_native(self) -> u16 {
                self as u16
            }

            /// Map a HID usage to its evdev keycode.
            ///
            /// The match is exhaustive over `HidUsage`, so a usage without
            /// an entry in the table below is a compile error.  The `Option`
            /// keeps the emission path honest should a future usage lack an
            /// evdev equivalent.
            pub const fn from_hid_usage(usage: HidUsage) -> Option<Self> {
                match usage {
                    $( HidUsage::$variant => Some(Self::$variant), )*
                }
            }

            /// Map this evdev keycode to its HID usage.
            pub const fn to_hid_usage(self) -> HidUsage {
                match self {
                    $( Self::$variant => HidUsage::$variant, )*
                }
            }
        }
    };
}

define_keycode! {
    // --- Modifiers ---
    LeftControl = 29;   // KEY_LEFTCTRL
    RightControl = 97;  // KEY_RIGHTCTRL
    LeftShift = 42;     // KEY_LEFTSHIFT
    RightShift = 54;    // KEY_RIGHTSHIFT
    LeftAlt = 56;       // KEY_LEFTALT
    RightAlt = 100;     // KEY_RIGHTALT
    LeftCommand = 125;  // KEY_LEFTMETA
    RightCommand = 126; // KEY_RIGHTMETA
    // --- Caps Lock ---
    CapsLock = 58; // KEY_CAPSLOCK
    // --- Editor / misc ---
    Tab = 15;       // KEY_TAB
    Space = 57;     // KEY_SPACE
    Return = 28;    // KEY_ENTER
    Backspace = 14; // KEY_BACKSPACE
    Delete = 111;   // KEY_DELETE
    Escape = 1;     // KEY_ESC
    // --- Navigation ---
    UpArrow = 103;    // KEY_UP
    DownArrow = 108;  // KEY_DOWN
    LeftArrow = 105;  // KEY_LEFT
    RightArrow = 106; // KEY_RIGHT
    PageUp = 104;     // KEY_PAGEUP
    PageDown = 109;   // KEY_PAGEDOWN
    Home = 102;       // KEY_HOME
    End = 107;        // KEY_END
    // --- Control/function cluster ---
    PrintScreen = 99; // KEY_PRINT
    ScrollLock = 70;  // KEY_SCROLLLOCK
    Pause = 119;      // KEY_PAUSE
    Insert = 110;     // KEY_INSERT
    // --- Application menu ---
    Menu = 358; // KEY_MENU
    // --- Function keys ---
    F1 = 59;  // KEY_F1
    F2 = 60;  // KEY_F2
    F3 = 61;  // KEY_F3
    F4 = 62;  // KEY_F4
    F5 = 63;  // KEY_F5
    F6 = 64;  // KEY_F6
    F7 = 65;  // KEY_F7
    F8 = 66;  // KEY_F8
    F9 = 67;  // KEY_F9
    F10 = 68; // KEY_F10
    F11 = 87; // KEY_F11
    F12 = 88; // KEY_F12
    // --- Letters ---
    A = 30;  // KEY_A
    B = 48;  // KEY_B
    C = 46;  // KEY_C
    D = 32;  // KEY_D
    E = 18;  // KEY_E
    F = 33;  // KEY_F
    G = 34;  // KEY_G
    H = 35;  // KEY_H
    I = 23;  // KEY_I
    J = 36;  // KEY_J
    K = 37;  // KEY_K
    L = 38;  // KEY_L
    M = 50;  // KEY_M
    N = 49;  // KEY_N
    O = 24;  // KEY_O
    P = 25;  // KEY_P
    Q = 16;  // KEY_Q
    R = 19;  // KEY_R
    S = 31;  // KEY_S
    T = 20;  // KEY_T
    U = 22;  // KEY_U
    V = 47;  // KEY_V
    W = 17;  // KEY_W
    X = 45;  // KEY_X
    Y = 21;  // KEY_Y
    Z = 44;  // KEY_Z
    // --- Numbers ---
    Number1 = 2;  // KEY_1
    Number2 = 3;  // KEY_2
    Number3 = 4;  // KEY_3
    Number4 = 5;  // KEY_4
    Number5 = 6;  // KEY_5
    Number6 = 7;  // KEY_6
    Number7 = 8;  // KEY_7
    Number8 = 9;  // KEY_8
    Number9 = 10; // KEY_9
    Number0 = 11; // KEY_0
    // --- Numpad ---
    Numpad0 = 82;        // KEY_KP0
    Numpad1 = 79;        // KEY_KP1
    Numpad2 = 80;        // KEY_KP2
    Numpad3 = 81;        // KEY_KP3
    Numpad4 = 75;        // KEY_KP4
    Numpad5 = 76;        // KEY_KP5
    Numpad6 = 77;        // KEY_KP6
    Numpad7 = 71;        // KEY_KP7
    Numpad8 = 72;        // KEY_KP8
    Numpad9 = 73;        // KEY_KP9
    NumpadDecimal = 83;  // KEY_KPDOT
    NumpadMultiply = 55; // KEY_KPASTERISK
    NumpadPlus = 78;     // KEY_KPPLUS
    NumpadDivide = 98;   // KEY_KPSLASH
    NumpadEnter = 96;    // KEY_KPENTER
    NumpadMinus = 74;    // KEY_KPMINUS
    NumLock = 69;        // KEY_NUMLOCK
    NumpadEqual = 117;   // KEY_KPEQUAL
    // --- Punctuation / symbols ---
    Minus = 12;         // KEY_MINUS
    Equal = 13;         // KEY_EQUAL
    BracketLeft = 26;   // KEY_LEFTBRACE
    BracketRight = 27;  // KEY_RIGHTBRACE
    Backslash = 43;     // KEY_BACKSLASH
    Semicolon = 39;     // KEY_SEMICOLON
    Quote = 40;         // KEY_APOSTROPHE
    Grave = 41;         // KEY_GRAVE
    Comma = 51;         // KEY_COMMA
    Slash = 53;         // KEY_SLASH
    Period = 52;        // KEY_DOT
    IsoExtra = 86;      // KEY_102ND
    // --- Consumer page (media controls) ---
    PlayPause = 164;      // KEY_PLAYPAUSE
    VolumeUp = 115;       // KEY_VOLUMEUP
    VolumeDown = 114;     // KEY_VOLUMEDOWN
    Mute = 113;           // KEY_MUTE
    NextTrack = 163;      // KEY_NEXTSONG
    PreviousTrack = 165;  // KEY_PREVIOUSSONG
    Stop = 166;           // KEY_STOPCD
    // --- Consumer page (display controls) ---
    BrightnessUp = 225;   // KEY_BRIGHTNESSUP
    BrightnessDown = 224; // KEY_BRIGHTNESSDOWN
}

/// Map a HID usage to the evdev `KEY_*` code used for emission on the
/// uinput virtual keyboard.
///
/// Returns `None` for usages without a stable evdev equivalent.
pub fn hid_usage_to_keycode(usage: HidUsage) -> Option<u16> {
    Keycode::from_hid_usage(usage).map(Keycode::as_native)
}

/// Map an evdev `KEY_*` code to its HID usage.
///
/// Input fallback for devices that do not emit `MSC_SCAN` (older kernels,
/// some virtual devices).  Covers the keyboard page subset plus the media
/// and display key codes the kernel derives from Consumer Page usages, so
/// that physical media keys can still be matched against rules.
pub fn keycode_to_hid_usage(code: u16) -> Option<HidUsage> {
    Keycode::from_native(code).map(Keycode::to_hid_usage)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn forward_table_covers_all_known_usages() {
        // Every usage in HidUsage::ALL must have an evdev code so that no
        // compiled rule output can be dropped on emission.
        for &usage in HidUsage::ALL {
            assert!(
                hid_usage_to_keycode(usage).is_some(),
                "missing evdev code for {}",
                usage.as_str()
            );
        }
    }

    #[test]
    fn tables_round_trip() {
        // Forward and reverse lookups must be exact inverses.
        for &usage in HidUsage::ALL {
            let code = hid_usage_to_keycode(usage).expect("forward table");
            assert_eq!(
                keycode_to_hid_usage(code),
                Some(usage),
                "round-trip failed for {}",
                usage.as_str()
            );
        }
    }

    #[test]
    fn no_duplicate_evdev_keycodes() {
        // Every usage has an evdev key code, and no two usages share one.
        // Uniqueness is what makes the reverse lookup (`from_native`) an
        // exact inverse of `from_hid_usage`.
        use std::collections::HashSet;
        let mut seen = HashSet::new();
        for usage in HidUsage::ALL.iter().copied() {
            let code = hid_usage_to_keycode(usage).unwrap_or_else(|| {
                panic!("missing evdev code for {}", usage.as_str())
            });
            assert!(
                seen.insert(code),
                "duplicate evdev code {code} for {}",
                usage.as_str(),
            );
        }
    }

    #[test]
    fn keycode_enum_round_trips_through_native_code() {
        for &usage in HidUsage::ALL {
            let keycode = Keycode::from_hid_usage(usage).expect("keycode");
            assert_eq!(
                Keycode::from_native(keycode.as_native()),
                Some(keycode)
            );
            assert_eq!(keycode.to_hid_usage(), usage);
        }
    }

    #[test]
    fn keyboard_page_values_match_kernel_header() {
        assert_eq!(
            hid_usage_to_keycode(HidUsage::A),
            Some(30) // KEY_A
        );
        assert_eq!(
            hid_usage_to_keycode(HidUsage::Space),
            Some(57) // KEY_SPACE
        );
        assert_eq!(
            hid_usage_to_keycode(HidUsage::LeftControl),
            Some(29) // KEY_LEFTCTRL
        );
        assert_eq!(
            hid_usage_to_keycode(HidUsage::NumpadEnter),
            Some(96) // KEY_KPENTER
        );
    }

    #[test]
    fn consumer_page_values_match_kernel_header() {
        assert_eq!(
            hid_usage_to_keycode(HidUsage::PlayPause),
            Some(164) // KEY_PLAYPAUSE
        );
        assert_eq!(
            hid_usage_to_keycode(HidUsage::VolumeUp),
            Some(115) // KEY_VOLUMEUP
        );
        assert_eq!(
            hid_usage_to_keycode(HidUsage::VolumeDown),
            Some(114) // KEY_VOLUMEDOWN
        );
        assert_eq!(
            hid_usage_to_keycode(HidUsage::Mute),
            Some(113) // KEY_MUTE
        );
        assert_eq!(
            hid_usage_to_keycode(HidUsage::NextTrack),
            Some(163) // KEY_NEXTSONG
        );
        assert_eq!(
            hid_usage_to_keycode(HidUsage::PreviousTrack),
            Some(165) // KEY_PREVIOUSSONG
        );
        assert_eq!(
            hid_usage_to_keycode(HidUsage::Stop),
            Some(166) // KEY_STOPCD
        );
    }

    #[test]
    fn reverse_table_resolves_media_key_codes() {
        assert_eq!(keycode_to_hid_usage(164), Some(HidUsage::PlayPause));
        assert_eq!(keycode_to_hid_usage(115), Some(HidUsage::VolumeUp));
        assert_eq!(keycode_to_hid_usage(114), Some(HidUsage::VolumeDown));
        assert_eq!(keycode_to_hid_usage(113), Some(HidUsage::Mute));
    }

    #[test]
    fn unknown_codes_return_none() {
        assert_eq!(keycode_to_hid_usage(0), None);
        assert_eq!(keycode_to_hid_usage(0x2FF), None);
    }
}
